/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as ServersIndexImport } from './routes/servers/index'
import { Route as ServersNameImport } from './routes/servers/$name'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const ServersIndexRoute = ServersIndexImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRoute,
} as any)

const ServersNameRoute = ServersNameImport.update({
  id: '/servers/$name',
  path: '/servers/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/servers/$name': {
      id: '/servers/$name'
      path: '/servers/$name'
      fullPath: '/servers/$name'
      preLoaderRoute: typeof ServersNameImport
      parentRoute: typeof rootRoute
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servers/$name': typeof ServersNameRoute
  '/servers': typeof ServersIndexRoute
  '/settings': typeof SettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servers/$name': typeof ServersNameRoute
  '/servers': typeof ServersIndexRoute
  '/settings': typeof SettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/servers/$name': typeof ServersNameRoute
  '/servers/': typeof ServersIndexRoute
  '/settings/': typeof SettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servers/$name' | '/servers' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servers/$name' | '/servers' | '/settings'
  id: '__root__' | '/' | '/servers/$name' | '/servers/' | '/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServersNameRoute: typeof ServersNameRoute
  ServersIndexRoute: typeof ServersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServersNameRoute: ServersNameRoute,
  ServersIndexRoute: ServersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/servers/$name",
        "/servers/",
        "/settings/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/servers/$name": {
      "filePath": "servers/$name.tsx"
    },
    "/servers/": {
      "filePath": "servers/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
