/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as SettingsIndexImport } from "./routes/settings/index";
import { Route as ServersIndexImport } from "./routes/servers/index";

// Create Virtual Routes

const ServersNameLazyImport = createFileRoute("/servers/$name")();

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const SettingsIndexRoute = SettingsIndexImport.update({
  path: "/settings/",
  getParentRoute: () => rootRoute,
} as any);

const ServersIndexRoute = ServersIndexImport.update({
  path: "/servers/",
  getParentRoute: () => rootRoute,
} as any);

const ServersNameLazyRoute = ServersNameLazyImport.update({
  path: "/servers/$name",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/servers/$name.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/servers/$name": {
      id: "/servers/$name";
      path: "/servers/$name";
      fullPath: "/servers/$name";
      preLoaderRoute: typeof ServersNameLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/servers/": {
      id: "/servers/";
      path: "/servers";
      fullPath: "/servers";
      preLoaderRoute: typeof ServersIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/settings/": {
      id: "/settings/";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ServersNameLazyRoute,
  ServersIndexRoute,
  SettingsIndexRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/servers/$name",
        "/servers/",
        "/settings/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/servers/$name": {
      "filePath": "servers/$name.lazy.tsx"
    },
    "/servers/": {
      "filePath": "servers/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
