/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as serversIndexImport } from "./routes/(servers)/index";

// Create Virtual Routes

const SettingsIndexLazyImport = createFileRoute("/settings/")();

// Create/Update Routes

const SettingsIndexLazyRoute = SettingsIndexLazyImport.update({
  path: "/settings/",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/settings/index.lazy").then((d) => d.Route),
);

const serversIndexRoute = serversIndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(servers)/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof serversIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/settings/": {
      id: "/settings/";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  serversIndexRoute,
  SettingsIndexLazyRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/settings/"
      ]
    },
    "/": {
      "filePath": "(servers)/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
